name: 'Push directory to branch gh-pages'
description: 'GitHub Action to commit and push a directory to the GitHub Pages branch gh-pages.'
author: 'angelstam'
branding:
  color: 'yellow'
  icon: code
inputs:
  source-pattern:
    description: 'The pattern used to match what to push to gh-pages'
    required: true
    default: 'dist/*'
runs: 
  using: 'composite'
  steps:
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run : git worktree add -b gh-pages gh-pages origin/gh-pages
      shell: bash
    - run : cp -r ${{ inputs.source-pattern }} gh-pages/
      shell: bash
    - run : git add --all
      working-directory: ./gh-pages
      shell: bash
    - run : git commit --allow-empty -m "Automatic Deploy run by GitHub Actions of commit ${{ github.sha }}."
      working-directory: ./gh-pages
      shell: bash
    - run : git push
      working-directory: ./gh-pages
      shell: bash
